export type NO_ACTION = 1;
export const NO_ACTION: NO_ACTION = 1;

export type ERR_NOT_IMPLEMENTED = -999;
export const ERR_NOT_IMPLEMENTED: ERR_NOT_IMPLEMENTED = -999;

export type ERR_ROOM_ENERGY_CAPACITY_NOT_ENOUGH = -20;
export const ERR_ROOM_ENERGY_CAPACITY_NOT_ENOUGH: ERR_ROOM_ENERGY_CAPACITY_NOT_ENOUGH = -20;
export type ERR_SPECIFIED_SPAWN_BUSY = -21;
export const ERR_SPECIFIED_SPAWN_BUSY: ERR_SPECIFIED_SPAWN_BUSY = -21;

export type ERR_CANNOT_PUSH_CREEP = -30;
export const ERR_CANNOT_PUSH_CREEP: ERR_CANNOT_PUSH_CREEP = -30;

export type ERR_SWARM_BUSY = -90;
export const ERR_SWARM_BUSY: ERR_SWARM_BUSY = -90;

export type ERR_SWARM_ROTATE_FAILED_1 = -100;
export const ERR_SWARM_ROTATE_FAILED_1: ERR_SWARM_ROTATE_FAILED_1 = -100;
export type ERR_SWARM_ROTATE_FAILED_2 = -101;
export const ERR_SWARM_ROTATE_FAILED_2: ERR_SWARM_ROTATE_FAILED_2 = -101;
export type ERR_SWARM_ROTATE_FAILED_3 = -102;
export const ERR_SWARM_ROTATE_FAILED_3: ERR_SWARM_ROTATE_FAILED_3 = -102;
export type ERR_SWARM_ROTATE_FAILED_4 = -103;
export const ERR_SWARM_ROTATE_FAILED_4: ERR_SWARM_ROTATE_FAILED_4 = -103;

export type ERR_SWARM_ROTATE_FAILED =
	| ERR_SWARM_ROTATE_FAILED_1
	| ERR_SWARM_ROTATE_FAILED_2
	| ERR_SWARM_ROTATE_FAILED_3
	| ERR_SWARM_ROTATE_FAILED_4;

export type OvermindReturnCode =
	| ScreepsReturnCode
	| NO_ACTION
	| ERR_SWARM_BUSY
	| ERR_ROOM_ENERGY_CAPACITY_NOT_ENOUGH
	| ERR_SPECIFIED_SPAWN_BUSY
	| ERR_CANNOT_PUSH_CREEP
	| ERR_NOT_IMPLEMENTED
	| ERR_SWARM_ROTATE_FAILED;

const errorMap: Record<OvermindReturnCode, string> = {
	"1": "NO_ACTION",
	"0": "OK",
	"-1": "ERR_NOT_OWNER",
	"-2": "ERR_NO_PATH",
	"-3": "ERR_NAME_EXISTS",
	"-4": "ERR_BUSY",
	"-5": "ERR_NOT_FOUND",
	"-6": "ERR_INSUFFICIENT",
	// "-6": "ERR_NOT_ENOUGH_ENERGY",
	// "-6": "ERR_NOT_ENOUGH_EXTENSIONS",
	// "-6": "ERR_NOT_ENOUGH_RESOURCES",
	"-7": "ERR_INVALID_TARGET",
	"-8": "ERR_FULL",
	"-9": "ERR_NOT_IN_RANGE",
	"-10": "ERR_INVALID_ARGS",
	"-11": "ERR_TIRED",
	"-12": "ERR_NO_BODYPART",
	"-14": "ERR_RCL_NOT_ENOUGH",
	"-15": "ERR_GCL_NOT_ENOUGH",
	"-20": "ERR_ROOM_ENERGY_CAPACITY_NOT_ENOUGH",
	"-21": "ERR_SPECIFIED_SPAWN_BUSY",
	"-30": "ERR_CANNOT_PUSH_CREEP",
	"-90": "ERR_SWARM_BUSY",
	"-100": "ERR_SWARM_ROTATE_FAILED_1",
	"-101": "ERR_SWARM_ROTATE_FAILED_2",
	"-102": "ERR_SWARM_ROTATE_FAILED_3",
	"-103": "ERR_SWARM_ROTATE_FAILED_4",
	"-999": "ERR_NOT_IMPLEMENTED",
	// "-1000": "ERR_NO_AVAILABLE_SPAWNER",
  };

  export function errorForCode(code: OvermindReturnCode) {
	return errorMap[code] ? `${errorMap[code]} (${code})` : `unknown (${code})`;
  }
